// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'atom/atom_test.dart' as atom_atom_test;
import 'basic/causal_tree_test.dart' as basic_causal_tree_test;
import 'basic/murmur3_test.dart' as basic_murmur3_test;
import 'basic/nested_hashing_test.dart' as basic_nested_hashing_test;
import 'logical_clock/en_decoding_test.dart' as logical_clock_en_decoding_test;
import 'logical_clock/hlcs_performance_test.dart' as logical_clock_hlcs_performance_test;
import 'logical_clock/hybrid_logical_clock_test.dart' as logical_clock_hybrid_logical_clock_test;
import 'logical_clock/logical_clock_test.dart' as logical_clock_logical_clock_test;
import 'sync/syncable_object_test.dart' as sync_syncable_object_test;

void main() {
  atom_atom_test.main();
  // basic_causal_tree_test.main();
  basic_murmur3_test.main();
  basic_nested_hashing_test.main();
  logical_clock_en_decoding_test.main();
  logical_clock_hlcs_performance_test.main();
  logical_clock_hybrid_logical_clock_test.main();
  logical_clock_logical_clock_test.main();
  sync_syncable_object_test.main();
}
