name: sync_layer
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  messagepack: ^0.1.1
  msgpack_dart: ^0.0.7
  meta: ^1.1.8
  logging: ^0.11.4

dev_dependencies:
  protoc_plugin: ^19.0.1
  archive: ^2.0.13
  lzma: ^0.4.0+2
  faker: ^1.2.1
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.9.0
