name: sync_layer
description: A sync layer implementation based on crdt concepts and Hyper logical clock
version: 0.0.1

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  msgpack_dart: ^0.0.7
  meta: ^1.1.8
  logger: ^0.9.1
  quick_log: ^0.4.0
  console_log_handler: ^1.1.6
  web_socket_channel: ^1.1.0
  archive: ^2.0.13


dev_dependencies:
  protoc_plugin: ^19.0.1
  lzma: ^0.4.0+2
  faker: ^1.2.1
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.9.0
  csv: ^4.0.3
