name: sync_layer
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  messagepack: ^0.1.1
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.9.0
